### ISSUE TITLE
Why show this on Windows 11

### ISSUE THREAD

**Issue by peter9811** [Sophia-Community/SophiApp#114]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [x] Refer to the [System requirements](https://github.com/Sophia-Community/SophiApp/blob/master/README.md#system-requirements);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [X] Attach a created log. You may find it in the `Logs` folder.

### Steps To Reproduce

Run the .exe

### Expected behavior

![image](https://user-images.githubusercontent.com/22783445/185691338-d2120a20-f5d2-476f-ae7e-85d7bfe929d2.png)

### Actual behaviour

idk

### Windows Version

Microsoft Windows 11 Pro 10.0.22000 22000

### SophiApp version

1.0.80.0

### SophiApp release type

SophiApp

### Logs

Windows 11 Pro 21H2 build 22000.856
Computer name: ADMINISTRATOR
User: Peter
User domain: ADMINISTRATOR
User culture: Spanish (Colombia)
User region: Colombia
App version: 1.0.80.0
App is release: True
App folder: "D:\Downloads\SophiApp\"
App localization: EN
App theme: DARK

19.08.2022 14:04:21 Debug mode is: False
19.08.2022 14:04:21 Active view is: Loading
19.08.2022 14:04:21 Advanced settings is visible: False
19.08.2022 14:04:21 The "UWP for all users" switch state is: UNCHECKED
19.08.2022 14:04:21 The OS conditions checkings started
19.08.2022 14:04:21 OsVersionCondition run result: True
19.08.2022 14:04:21 The next condition to be run: OsBuildVersionCondition
19.08.2022 14:04:21 OsBuildVersionCondition run result: True
19.08.2022 14:04:21 The next condition to be run: OsFilesCorruptedCondition
19.08.2022 14:04:21 OsFilesCorruptedCondition run result: False
19.08.2022 14:04:21 The next condition to be run: RebootRequiredCondition
19.08.2022 14:04:22 Active view is: OsFilesCorrupted
19.08.2022 14:04:22 It took 0 second(s) to check the OS conditions

**Comment by farag2** [comment]
Hi! It is shown if some services were removed from Windows. Let's check: run this as admin in PowerShell one by one and send output

```powershell
Get-CimInstance -ClassName MSFT_MpComputerStatus -Namespace root/microsoft/windows/defender
```

```powershell
Get-Service -Name Windefend, SecurityHealthService, wscsvc
```

**Comment by peter9811** [comment]
1.
AMEngineVersion                 : 0.0.0.0
AMProductVersion                : 4.18.2104.10
AMRunningMode                   : Not running
AMServiceEnabled                : False
AMServiceVersion                : 0.0.0.0
AntispywareEnabled              : False
AntispywareSignatureAge         : 4294967295
AntispywareSignatureLastUpdated :
AntispywareSignatureVersion     : 0.0.0.0
AntivirusEnabled                : False
AntivirusSignatureAge           : 4294967295
AntivirusSignatureLastUpdated   :
AntivirusSignatureVersion       : 0.0.0.0
BehaviorMonitorEnabled          : False
ComputerID                      : A3A82DA5-F27D-4961-B0FE-DF126D0EBD54
ComputerState                   : 0
FullScanAge                     : 4294967295
FullScanEndTime                 :
FullScanStartTime               :
IoavProtectionEnabled           : False
IsTamperProtected               : False
IsVirtualMachine                : False
LastFullScanSource              : 0
LastQuickScanSource             : 0
NISEnabled                      : False
NISEngineVersion                : 0.0.0.0
NISSignatureAge                 : 4294967295
NISSignatureLastUpdated         :
NISSignatureVersion             : 0.0.0.0
OnAccessProtectionEnabled       : False
QuickScanAge                    : 4294967295
QuickScanEndTime                :
QuickScanStartTime              :
RealTimeProtectionEnabled       : False
RealTimeScanDirection           : 0
TamperProtectionSource          : Signatures
PSComputerName                  :

2.
Get-Service: Cannot find any service with service name 'SecurityHealthService'.

Status   Name               DisplayName
------   ----               -----------
Stopped  Windefend          Servicio Antivirus de Microsoft Defen…
Stopped  wscsvc             Centro de seguridad

**Comment by farag2** [comment]
You removed one Defender related service. That's why launching this app was failed. This is the Bible: if Windows is destroyed, we play safe and block ability. How did it happen that Defender was destroyed and WMI cache with it?

**Comment by peter9811** [comment]
I uninstalled it myself, because it conflicts with some activators or removes them without asking and well, I use independent antivirus

**Comment by farag2** [comment]
Ah, removed? :) So add your activators (I know this feeling) to the exclusion list is for the weaks? :) Why you didn't do that?
PowerShell is a powerful to manage Defender. Even if you do not know it, why you didn't just added your files manually? this is so strange.
Anyway, the issue, cannot be fixed. My advice: re-install the OS, deactivate Defender—not remove it (if you really want it). Add your activators and so on manually or by code to the exclusion list. Profit!
