### ISSUE TITLE
Ungroup icons on the taskbar in Windows 11

### ISSUE THREAD

**Issue by chertilin** [Sophia-Community/SophiApp#115]
### Your Idea

Create checkbox for switch off grouping icons on the taskbar.

In Windows 11, this cannot be done.

### Windows Version

Windows 11

**Comment by farag2** [comment]
There is no built-in method for Windows 11 to do such thing. So no way...
I think you may install [StartAllBack](https://www.androidauthority.com/ungroup-icons-taskbar-windows-11-3149488), disable a custom Start from the app but enable feature to ungroup icons.

**Comment by farag2** [comment]
This is what you need: https://windhawk.net/mods/taskbar-grouping
