### ISSUE TITLE
Why is the newtonsoft.json.dll modified?

### ISSUE THREAD

**Issue by jobrien78** [Sophia-Community/SophiApp#128]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [System requirements](https://github.com/Sophia-Community/SophiApp/blob/master/README.md#system-requirements);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [X] Attach a created log. You may find it in the `Logs` folder.

### Steps To Reproduce

Hi, I had a look at the dlls and in particular newtonsoft.json.dll which comes packed with the app and am finding its hash doesnt match the one that is supposedly have been downloaded from the official JamesNK/Newtonsoft.Json repo during the build process (https://github.com/Sophia-Community/SophiApp/blob/f0e2c942e2c95b9a7ea1d3c44e12fd928ad9533c/SophiApp/Scripts/Get-BinaryFiles.ps1#L84-L87)

![image](https://user-images.githubusercontent.com/112982741/188735066-aeab50bd-c70a-4e7b-a40a-3eca1ff5102c.png)

Can you explain why the dll is modified?

Also why isn't this dll at least be downloaded via NuGet?

### Expected behavior

N/A

### Actual behaviour

N/A

### Windows Version

Win 10

### SophiApp version

Current

### SophiApp release type

SophiApp

### Logs

N/A

**Comment by farag2** [comment]
Hm... I/we do not modify any of DLLs. Everything is automated. Let me check...

**Comment by farag2** [comment]
Yeah, they're really not equal. But how?.. O_O

![изображение](https://user-images.githubusercontent.com/10544660/188737143-bfccca8d-445f-439c-8cdb-fc961fb4a641.png)

**Comment by farag2** [comment]
All that I understood is that DLL in the SophiApp folder is equal to the Nuget one, but not equal to the GitHub one at the same time. Also the GitHub dll isn't equal to the Nuget dll. They even have different timestamp.

**Comment by jobrien78** [comment]
I haven't tried the one from NuGet, but running your get binary script I am also able to get the expected hash which should be in the SophiApp.

**Comment by farag2** [comment]
I will ask my colleague tomorrow, how it could happen when we download one dll but get another after compilation. I'm really puzzled.

**Comment by jobrien78** [comment]
OK, thank you.

**Comment by farag2** [comment]
Fixed with #131
