### ISSUE TITLE
Startup issue

### ISSUE THREAD

**Issue by LeonidEfremov** [Sophia-Community/SophiApp#145]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [System requirements](https://github.com/Sophia-Community/SophiApp/blob/master/README.md#system-requirements);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [X] Attach a created log. You may find it in the `Logs` folder.

### Steps To Reproduce

1. Just start app
2. App is starting
3. Window is closed after few seconds
4. No logs in ./Logs folder

Windows 11 22H2

### Expected behavior

App is started

### Actual behaviour

Cant start

### Windows Version

Win 11 22H2 22621.608

### SophiApp version

1.0.84.0

### SophiApp release type

SophiApp

### Logs

No logs provided by app
[2.txt](https://github.com/Sophia-Community/SophiApp/files/9709504/2.txt)
[1.txt](https://github.com/Sophia-Community/SophiApp/files/9709505/1.txt)

**Comment by farag2** [comment]
Obviously, something is wrong with you system. If it cannot even launch the app... Such logs hardly can help us. :(

**Comment by farag2** [comment]
```Exception Info: System.IO.FileNotFoundException at SophiApp.ViewModels.AppVM.DeserializeTextedElementsAsync>b__77_0()```

Your system even cannot deserialize object. So manage with it first. We cannot help you in this case. Or, what's better, try to re-download the archive. Sometimes it helps. :)

**Comment by LeonidEfremov** [comment]
"Windows issue", "Your system can't deserialize object"  - it's brilliant =)) Worst answer ever. Are you developer?
