### ISSUE TITLE
Better headers

### ISSUE THREAD

**Issue by JokeUrSelf** [Sophia-Community/SophiApp#150]
### Your Idea

Currently headers have exactly the same font as its options. Even though headers have underline, still It is difficult to distinguish them from the options above. I suggest making headers bold and in-between 2 lines istead of just 1 underline.

![image](https://user-images.githubusercontent.com/81817136/199047868-d93fcdab-b6a1-4022-b83e-d9b78d1fe9c7.png)

### SophiApp Version

1.0.86

### Windows Version

Doesn't matter

**Comment by TheBossMagnus** [comment]
> 

I 100% agree, but a 2.0 version is in design so i think the whole gui will change....

**Comment by farag2** [comment]
But I'm not against of bold titles in 1.0.87. :)
First sketches of 2.0 will be revealed very soon))

**Comment by Inestic** [comment]
What do you think?

![SophiAppLight](https://user-images.githubusercontent.com/50652175/199280881-33d062ac-5132-4087-a5a0-e37393955fd2.png)

![SophiAppDark](https://user-images.githubusercontent.com/50652175/199280897-e85b3284-1343-4fd2-bb8a-2788e31a39dc.png)

**Comment by JokeUrSelf** [comment]
NIce! Can't wait to see, how 2.0 version is gonna look like 👀

**Comment by farag2** [comment]
It will blow your mind. But today UX designer has a headache. 😿
