### ISSUE TITLE
How to keep optional diagnostic data turned on for screenshots/video recording on feedback hub.

### ISSUE THREAD

**Issue by bigplayer-ai** [Sophia-Community/SophiApp#173]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [System requirements](https://github.com/Sophia-Community/SophiApp/blob/master/README.md#system-requirements);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [X] Attach a created log. You may find it in the `Logs` folder.

### Steps To Reproduce

Hey,
How can I keep optional diagnostic data turned on, So I can attach screenshot/recordings using feedback hub.
1) fix issues using sophiapp
2) you can't attach recording/screenshots on feedback hub
3) the option optional diagnostic grayed out (your organization prevents sending diagnostic data to microsoft)
![image](https://user-images.githubusercontent.com/119108387/215267521-ecc66424-30ce-4379-9417-e0a4cad18476.png)

### Expected behavior

to attach videos/screenshots in feedback hub.

### Actual behaviour

I can't attach videos/screenshots in feedback hub.
also optional diagnositc data is grayed out.

### Windows Version

WIN11 22H2 Build 22621.1194

### SophiApp version

1.0.93

### SophiApp release type

SophiApp

### Logs

[SophiApp-YAZANVOSTRO-133193762820152842.txt](https://github.com/Sophia-Community/SophiApp/files/10527287/SophiApp-YAZANVOSTRO-133193762820152842.txt)
[SophiApp-YAZANVOSTRO-133193797516198767.txt](https://github.com/Sophia-Community/SophiApp/files/10527288/SophiApp-YAZANVOSTRO-133193797516198767.txt)

**Comment by farag2** [comment]
I think, this is by Windows Insider program design: you must enable telemetry sending to be able to attach files to the Insider Hub. Am I right?

**Comment by farag2** [comment]
Anyway, I will try to reproduce the bug on an Insider VM.

**Comment by bigplayer-ai** [comment]
I am not on insider windows 11, Just got a new pc with this version installed.

**Comment by farag2** [comment]
Could I take a look remotely on the bug? Ping me please via Telegram https://t.me/sanctuary_d or Discord sanctuary_s#6351

**Comment by bigplayer-ai** [comment]
> Anyway, I will try to reproduce the bug on an Insider VM.

Ok after enabling telemetry services everything works fine in feedback hub.
thanks

**Comment by bigplayer-ai** [comment]
> Ah, diagtrack influences on this action? wow

You should add a comment for this, I had alot of troubleshooting going on, Turns out telemetry option to blame.

**Comment by farag2** [comment]
Could attach a screenshot how that error lokks like to make it more clear for me?

**Comment by bigplayer-ai** [comment]
> Could attach a screenshot how that error lokks like to make it more clear for me?

there is a photo attached in previous comments.

**Comment by farag2** [comment]
I've changed the description already in 1.0.94.
