### ISSUE TITLE
Add option to remove "Windows Security" from start menu

### ISSUE THREAD

**Issue by anonymous-one** [Sophia-Community/SophiApp#184]
### Your Idea

Pretty simple, I would love to be able to remove the Windows Security item from the start menu.
![Untitled](https://github.com/Sophia-Community/SophiApp/assets/4963653/1533aba7-d5a2-439b-902a-a7560b76b0d7)

I have looked around and the only fix I found on superuser.com did not do the trick.

### Windows Version

Windows 10 21H2

**Comment by farag2** [comment]
It won't be added. We do not break Windows.
