### ISSUE TITLE
Doesn't work on Windows 11 25905

### ISSUE THREAD

**Issue by abbaccadd0** [Sophia-Community/SophiApp#188]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [System requirements](https://github.com/Sophia-Community/SophiApp/blob/master/README.md#system-requirements);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [X] Attach a created log. You may find it in the `Logs` folder.

### Expected behavior

SophiApp support Windows 11 23H2 25206+, so it should work on 25905 because 25905 > 25206
🤔But it not
I opened it, and it said  
> Your version of Windows is out of date.
The minimum supported Windows 11 Insider Preview build is 22509
Please run Windows Update to update the OS to the latest version.

### Actual behaviour

It should work well.

### Windows Version

Windows 11 Pro for Workstation Insider Preview 23H2 25905.1000  
Windows Feature Experience Pack 1000.25905.1000.0

### SophiApp version

1.0.96

### SophiApp release type

SophiApp Beta

### Logs

> Windows 10 Pro for Workstations 23H2 build 25905.1000
Computer name: DESKTOP-AU4CC12
User: altria3484
User domain: DESKTOP-AU4CC12
User culture: Chinese (Simplified, Mainland China)
User region: China
App version: 1.0.96.0
App is release: False
App folder: "D:\Users\altria3484\Desktop\Software\Tools\SophiApp\"
App localization: EN
App theme: LIGHT  

> 23.07.2023 17:23:40 Debug mode is: False
23.07.2023 17:23:40 Active view is: Loading
23.07.2023 17:23:40 Advanced settings is visible: False
23.07.2023 17:23:40 The "UWP for all users" switch state is: UNCHECKED
23.07.2023 17:23:40 The OS conditions check started
23.07.2023 17:23:40 OsVersionCondition run result: True
23.07.2023 17:23:40 The next condition to be run: OsBuildVersionCondition
23.07.2023 17:23:40 OsBuildVersionCondition run result: False
23.07.2023 17:23:40 The next condition to be run: OsFilesCorruptedCondition
23.07.2023 17:23:40 Active view is: OsBuildVersion
23.07.2023 17:23:40 It took 0 second(s) to check the OS conditions

**Comment by farag2** [comment]
😭

**Comment by farag2** [comment]
Will be fixed this week.

**Comment by farag2** [comment]
Fixed in 1.0.97.
