### ISSUE TITLE
SophiApp 1.0.97.0 don' work on Windows 10 Pro 22H2 (19045.2965)

### ISSUE THREAD

**Issue by CaptainQuake** [Sophia-Community/SophiApp#192]
### Prerequisites

- [x] Verify that this is not a Windows issue;
- [X] Refer to the [System requirements](https://github.com/Sophia-Community/SophiApp/blob/master/README.md#system-requirements);
- [X] I do not use a homebrew Windows image;
- [ ] I did not tweak Windows before that could cause system instability;
- [X] Attach a created log. You may find it in the `Logs` folder.

### Steps To Reproduce

1. Start the program
![2023-07-27_113705](https://github.com/Sophia-Community/SophiApp/assets/75237891/91251560-5b5b-440e-b7c1-6b53639c29d2)

### Expected behavior

After launching the program should work

### Actual behaviour

But it doesn't work

### Windows Version

Windows 10 Pro 22H2 19045.2965

### SophiApp version

SophiApp 1.0.97

### SophiApp release type

SophiApp

### Logs

No log files

**Comment by farag2** [comment]
Fixed typos in description.
