### ISSUE TITLE
Empty recycle bin is grayed out

### ISSUE THREAD

**Issue by JovenCalixto** [Sophia-Community/SophiApp#202]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [System requirements](https://github.com/Sophia-Community/SophiApp/blob/master/README.md#system-requirements);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [X] Attach a created log. You may find it in the `Logs` folder.

### Steps To Reproduce

1. I used SophiApp for the first time.
2. I disabled all diagnosis tasks in the privacy tab except for XblGameSaveTask
3. I removed UWP apps that I didn't use like Phone Link, Help Center and such.

### Expected behavior

I expected the program to work (which it did) and the parts of the system I didn't change to remain the same they were before executing the script, being it the "empty recycle bin" option working.

### Actual behaviour

The "empty recycle bin" option that appears when right-clicking the bin is grayed out, although I can still enter it and remove the files inside of it manually. i'll update all the logs, but the problem should have started in the oldest ones, as the newer ones were in order to revert the changes made (except for the uninstalled apps) to see if that works and then turning the changes back on after seeing it didn't work.

Thank you

P.D: Also I have another "bug" inside the app that makes it crash each time I search for something, I don't know if that is a known bug and it doesn't concern me much, but I'll inform of it just in case.

### Windows Version

Windows 10 Home 22H2 19045.3803

### SophiApp version

1.0.97

### SophiApp release type

SophiApp

### Logs

[SophiApp-DESKTOP-RP4CSL6-133469806302002413.txt](https://github.com/Sophia-Community/SophiApp/files/13670647/SophiApp-DESKTOP-RP4CSL6-133469806302002413.txt)
[SophiApp-DESKTOP-RP4CSL6-133469809753519423.txt](https://github.com/Sophia-Community/SophiApp/files/13670648/SophiApp-DESKTOP-RP4CSL6-133469809753519423.txt)
[SophiApp-DESKTOP-RP4CSL6-133469817637465422.txt](https://github.com/Sophia-Community/SophiApp/files/13670649/SophiApp-DESKTOP-RP4CSL6-133469817637465422.txt)
[SophiApp-DESKTOP-RP4CSL6-133469710412912146.txt](https://github.com/Sophia-Community/SophiApp/files/13670650/SophiApp-DESKTOP-RP4CSL6-133469710412912146.txt)
[SophiApp-DESKTOP-RP4CSL6-133469718220258419.txt](https://github.com/Sophia-Community/SophiApp/files/13670651/SophiApp-DESKTOP-RP4CSL6-133469718220258419.txt)
[SophiApp-DESKTOP-RP4CSL6-133469719777975295.txt](https://github.com/Sophia-Community/SophiApp/files/13670652/SophiApp-DESKTOP-RP4CSL6-133469719777975295.txt)
[SophiApp-DESKTOP-RP4CSL6-133469770168521066.txt](https://github.com/Sophia-Community/SophiApp/files/13670653/SophiApp-DESKTOP-RP4CSL6-133469770168521066.txt)

**Comment by farag2** [comment]
The app has no effect on recycle bin behaviour. Really. It just has no such code. Which apps did you use before?

**Comment by farag2** [comment]
Actually, the app is pretty outdated. But it doesn't grrey out context menu item))
We're cooking SophiApp 2.0. https://t.me/SophiaNews/2492

Anyway, could you check policies in the registry? If not, I can help you remotely via TeamViewer. I think, this is a policy applied by another tweaker.

**Comment by JovenCalixto** [comment]
> The app has no effect on recycle bin behaviour. Really. It just has no such code. Which apps did you use before?

I know it's strange, but I didn't use any optimizer or app before on that Windows I just turned on the computer, ran SophiApp and then update GPU drivers (which I think, cannot affect the behaviour of the bin) so I don't know what the issue can be.

Apart from that the script is great, thank you for your hard work. But I found strange that after using it, without applying any option regarding the recycle bin (because I think none exist) the option became grayed out.

Sorry for being so inaccurate. But I think those were the only things I did yesterday with my computer as I was all the day out.

Thank you for your fast response.

**Comment by farag2** [comment]
I'd stay with the previous statement: there's no such code))
Anyway, I can check renotely, if you wish.

**Comment by JovenCalixto** [comment]
I don't understand what checking remotely is (if I need to be in a call, I cannot until tomorrow). But I would appreciate it if it isn't inconvenient.

Thank you

**Comment by farag2** [comment]
https://www.tenforums.com/performance-maintenance/154438-empty-recycle-bin-always-greyed-out.html

Google being in the underground. I guess, this may be your case.

**Comment by farag2** [comment]
https://www.tenforums.com/tutorials/94946-fix-corrupted-recycle-bin-windows.html

**Comment by JovenCalixto** [comment]
Ok, but as I won't be able to access my PC until this night because of work (I'm writing this through my phone). Also, I've never used TeamViewer, but I'll try to learn about it and installed it this night so I can prepare everything for your tomorrow.

Thank you and sorry for the inconveniences.

**Comment by farag2** [comment]
No problem. I'm on vacation)

https://en.wikipedia.org/wiki/TeamViewer

**Comment by JovenCalixto** [comment]
Ok, thank you so much for your disponibility and sorry for disturbing your vacation.

> https://www.tenforums.com/tutorials/94946-fix-corrupted-recycle-bin-windows.html

About this, I already searched and tried this, but it didn't work.
I'll try to do it again step by step this night to see if it works and I don't have to disturb you any longer.

**Comment by JovenCalixto** [comment]
> No heed in call. Just TeamViewer:) Ping me when you're available.

Ok, I installed TeamViewer and its ready for tomorrow.
Sorry for what I'm going to ask, as ibut I've written few issues on Github, but how can I ping you?

P.D: Also I tried doing again the steps on the corrupted bin link you passed me and they didn't work. Also I tried doing a repair upgrade through Windows ISO and it didn't work if that information helps.

Thank you

**Comment by farag2** [comment]
Message me in Telegram: sanctuary_d

**Comment by JovenCalixto** [comment]
Ok, mine is the same as my Github name

**Comment by farag2** [comment]
Fixed. just something went wrong))
