### ISSUE TITLE
"Your version of Windows is out of date" error message

### ISSUE THREAD

**Issue by brian5-1** [Sophia-Community/SophiApp#205]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [System requirements](https://github.com/Sophia-Community/SophiApp/blob/master/README.md#system-requirements);
- [X] I do not use a homebrew Windows image;
- [X] I did not tweak Windows before that could cause system instability;
- [X] Attach a created log. You may find it in the `Logs` folder.

### Steps To Reproduce

1. Start SophiApp 1.0.97

### Expected behavior

SophiApp menus should be functional

### Actual behaviour

![error](https://github.com/Sophia-Community/SophiApp/assets/104744128/e2bb1b81-d474-4c44-91b3-092cf8c6d06f)
I get the attached error "Your version of Windows is out of date."  Obviously, I have a much higher version (26120) so am not clear on how to resolve.   Thanks

### Windows Version

Windows 11 Pro, version 24H2, OS Build 26120.461

### SophiApp version

1.0.97

### SophiApp release type

SophiApp

### Logs

Windows 10 Pro 24H2 build 26120.461
Computer name: OCTOPUS
User: brian
User domain: OCTOPUS
User culture: English (United States)
User region: United States
App version: 1.0.97.0
App is release: True
App folder: "C:\opt\SophiApp\"
App localization: EN
App theme: DARK

08.05.2024 16:03:26 Debug mode is: False
08.05.2024 16:03:26 Active view is: Loading
08.05.2024 16:03:26 Advanced settings is visible: False
08.05.2024 16:03:26 The "UWP for all users" switch state is: UNCHECKED
08.05.2024 16:03:26 The OS conditions check started
08.05.2024 16:03:26 OsVersionCondition run result: True
08.05.2024 16:03:26 The next condition to be run: OsBuildVersionCondition
08.05.2024 16:03:26 OsBuildVersionCondition run result: False
08.05.2024 16:03:26 The next condition to be run: OsFilesCorruptedCondition
08.05.2024 16:03:26 Active view is: OsBuildVersion
08.05.2024 16:03:27 It took 0 second(s) to check the OS conditions

**Comment by farag2** [comment]
Hi. The SophiApp 1.x development has been stopped in order to create 2.0 version. This bug will be fixed automatically with a 2.0 release.

https://github.com/Sophia-Community/SophiApp?tab=readme-ov-file#sophiapp-20

**Comment by brian5-1** [comment]
Dmitry, Thanks for your prompt response. That's fine.

**Comment by farag2** [comment]
I'd definitely use Sophia Script once the app will be released and tested. If everything is fine, we will complete the first public build somewhere in September. :)

**Comment by brian5-1** [comment]
Yes, will be doing that. Thanks
