### ISSUE TITLE
Radio button UI suggestion

### ISSUE THREAD

**Issue by versedwildcat** [Sophia-Community/SophiApp#23]
This is the current UI:
![image](https://user-images.githubusercontent.com/96885152/147781473-20580147-e3e5-406e-b1a8-4253f8114255.png)

Consider moving the first separator above the option it corresponds to and adding a second one, like this:
![image](https://user-images.githubusercontent.com/96885152/147782393-879e1920-0eef-43ad-8227-aae2e95b0c15.png)

And possibly moving the buttons to the left, as such:
![image](https://user-images.githubusercontent.com/96885152/147782349-0d4f267e-7e29-49fd-9fd5-b3fb028fe504.png)

**Comment by farag2** [comment]
Firstly, we need to fix 28 bugs in the code. After that, we will think over your suggestion. :)

**Comment by Inestic** [comment]
Thanks for your suggestions! I added a second line to visually limit the height of the element.

![s1](https://user-images.githubusercontent.com/50652175/149137647-30db9d04-afbd-4c93-8b17-83018432199c.png)
