### ISSUE TITLE
Cannot maximize/restore window || Support Title Bar buttons

### ISSUE THREAD

**Issue by versedwildcat** [Sophia-Community/SophiApp#24]
Currently, there is no way to maximize the app. (Or restore to previous window size)

Support the Windows title buttons (![image](https://user-images.githubusercontent.com/96885152/147784084-ffcb9f1a-ab20-4ecb-8b93-84b40ecba4a0.png))
Additionally, since there is no title bar, you cannot snap the window at all.

**Comment by Inestic** [comment]
Added a maximize/restore button. Use window header (highlighted in red) to drag, works like a normal window.

![image](https://i.imgur.com/oiBuq6j.png)
