### ISSUE TITLE
Optional flag to disable warning screen

### ISSUE THREAD

**Issue by Lovecrafts-Cat** [Sophia-Community/SophiApp#30]
![2022-01-22 21_37_14 SophiApp mJdIn](https://user-images.githubusercontent.com/52252627/150654631-7ca6e78c-71dd-46c9-8cae-d8022babfc8a.png)

I know that it's important to prevent end users form damaging their system, but it would be nice to have a setting/flag to disable this check.

I have previously modified my installation (even though the tool listed on the banner is not the same I used), but reinstalling the OS to try this out is not really the best option, at least for me.

I am sure other users may have modified their install as well, so it'd be nice to have this option, even if it's behind a config or a big red warning.

**Comment by farag2** [comment]
We  thought about this. But wait until the 2.0 release somewhere in late 2022.

**Comment by farag2** [comment]
Also, 1.0.6 much more stable than the initial 1.0 beta 1. :)

**Comment by Lovecrafts-Cat** [comment]
> We thought about this. But wait until the 2.0 release somewhere in late 2022.
> Also, 1.0.6 much more stable than the initial 1.0 beta 1. :)

Alright, thanks for the info, really appreciate it :)
Feel free to close this now or at 2.0's release 👍

**Comment by farag2** [comment]
And 1.0.6 has a new category)

**Comment by farag2** [comment]
Added in some of 1.0.0.1x build. :)

**Comment by Lovecrafts-Cat** [comment]
I may be wrong, but there doesn't seem to be an option to skip the screen.
Is there something else I'm supposed to do to bypass the warning?
![2022-02-15 23_16_28 SophiApp 7sH7R](https://user-images.githubusercontent.com/52252627/154158935-919add98-6dbd-4a99-aff8-5d8a84824c28.png)

```
15.02.2022 23:08:00 Debug mode is: False
15.02.2022 23:08:00 Advanced settings is visible: False
15.02.2022 23:08:00 Active view is: Loading
15.02.2022 23:08:00 Uwp for all users switch state is: UNCHECKED
15.02.2022 23:08:00 Starting the initial OS conditions
15.02.2022 23:08:00 OsBuildVersion is: True
15.02.2022 23:08:00 UpdateBuildRevision is: True
15.02.2022 23:08:00 OneInstanceOnly is: True
15.02.2022 23:08:00 IsSingleSession is: True
15.02.2022 23:08:00 LoggedUserAdmin is: True
15.02.2022 23:08:00 OsNotInfected is: True
15.02.2022 23:08:00 Windows10DebloaterNotUsed is: False
15.02.2022 23:08:00 Active view is: Windows10DebloaterNotUsed
15.02.2022 23:08:00 It took 0 second(s) to initialize Os conditions
```
