### ISSUE TITLE
Says there's an update, and disallows using when firewall access is not granted.

### ISSUE THREAD

**Issue by Chaython** [Sophia-Community/SophiApp#34]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [System requirements](https://github.com/Sophia-Community/SophiApp/blob/master/README.md#system-requirements);
- [X] Attach a created log. You may find it in the app folder

### Steps To Reproduce

Launch SophiApp
Block in firewall
Get a message in app that it found an update...

### Expected behavior

Update checks should be optional
App should work regardless of if there's a newer version or not

### SophiApp version

1.0.0.22 BETA 2 PR

### Windows Version

Windows 11 Enterprise 21H2 build: 10.0.22000.527

### Logs

Windows 11 Enterprise 21H2 build: 10.0.22000.527
Computer name: x
Registered organization: 
Registered owner: 
Current user: x
User domain: x
User culture: English (United States)
User region: United States
App version: 1.0.0.22
App is release: False
App folder: "D:\Downloads\SophiApp\SophiApp\"
App localization: EN
App theme: DARK

18.02.2022 10:16:55 An error occurred while checking for an update
18.02.2022 10:16:55 Error information: Unable to connect to the remote server
18.02.2022 10:16:55 The method that caused the error: GetResponse

18.02.2022 10:16:55 Debug mode is: False
18.02.2022 10:16:55 Active view is: Loading
18.02.2022 10:16:55 Advanced settings is visible: False
18.02.2022 10:16:55 The "UWP for all users" switch state is: UNCHECKED
18.02.2022 10:16:55 Starting the OS conditions check
18.02.2022 10:16:55 NewVersion is has problem: True
18.02.2022 10:16:55 Active view is: NewVersion
18.02.2022 10:16:55 It took 0 second(s) to Os conditions checks

**Comment by farag2** [comment]
Confirm. :godmode:

**Comment by Inestic** [comment]
Fixed. Thank you for issue and log.
