### ISSUE TITLE
SophiApp crash

### ISSUE THREAD

**Issue by pedrodj7878** [Sophia-Community/SophiApp#39]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [System requirements](https://github.com/Sophia-Community/SophiApp/blob/master/README.md#system-requirements);
- [ ] Attach a created log. You may find it in the app folder

### Expected behavior

Dear Team
++++++++++++
My Windows 10 
Edizione	Windows 10 Home
Versione	21H1
Data installazione:	‎20/‎05/‎2021
Build sistema operativo	19043.1586
Esperienza	Windows Feature Experience Pack 120.2212.4170.0
++++++++++++
when I run the .exe with admin right, tools start but close itself after few seconds.

How can i fix?

### SophiApp version

1.0.0.13 beta 2

### Windows Version

Windows 10 

### Logs

PS C:\Program Files\PowerShell\7> $HashTable = @{
>>    LogName = "Application"
>>    Id      = "1026"
>> }
PS C:\Program Files\PowerShell\7> Get-WinEvent -FilterHashtable $HashTable | Where-Object -FilterScript {($_.Level -eq "2") -and ($_.Message -match "SophiApp.exe")} | Select-Object -First 1 | Format-List -Property *

Message              : Applicazione: SophiApp.exe
                       Versione framework: v4.0.30319
                       Descrizione: il processo è stato terminato a causa di un'eccezione non gestita.
                       Informazioni sull'eccezione: System.BadImageFormatException
                          in SophiApp.Helpers.UwpHelper.GetPackagesDto(Boolean)
                          in SophiApp.ViewModels.AppVM.GetUwpElements()
                          in System.Threading.Tasks.Task.Execute()
                          in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                          in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System
                       .Threading.Tasks.Task)
                          in SophiApp.ViewModels.AppVM+<InitializeUwpElementsAsync>d__75.MoveNext()
                          in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                          in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System
                       .Threading.Tasks.Task)
                          in SophiApp.ViewModels.AppVM+<Initialize>d__102.MoveNext()
                          in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                          in System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate,
                       System.Object, Int32)
                          in System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate,
                       System.Object, Int32, System.Delegate)
                          in System.Windows.Threading.DispatcherOperation.InvokeImpl()
                          in MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
                          in System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext,
                       System.Threading.ContextCallback, System.Object, Boolean)
                          in System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext,
                       System.Threading.ContextCallback, System.Object, Boolean)
                          in System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext,
                       System.Threading.ContextCallback, System.Object)
                          in MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionCo
                       ntext, System.Threading.ContextCallback, System.Object)
                          in System.Windows.Threading.DispatcherOperation.Invoke()
                          in System.Windows.Threading.Dispatcher.ProcessQueue()
                          in System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean
                       ByRef)
                          in MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
                          in MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
                          in System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate,
                       System.Object, Int32)
                          in System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate,
                       System.Object, Int32, System.Delegate)
                          in System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPr
                       iority, System.TimeSpan, System.Delegate, System.Object, Int32)
                          in MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
                          in MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
                          in
                       System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
                          in System.Windows.Application.RunDispatcher(System.Object)
                          in System.Windows.Application.RunInternal(System.Windows.Window)
                          in SophiApp.App.Main()

Id                   : 1026
Version              : 0
Qualifiers           : 0
Level                : 2
Task                 : 0
Opcode               : 0
Keywords             : 36028797018963968
RecordId             : 34385
ProviderName         : .NET Runtime
ProviderId           :
LogName              : Application
ProcessId            : 0
ThreadId             : 0
MachineName          : DESKTOP-DDJ9GB4
UserId               :
TimeCreated          : 21/03/2022 17:56:29
ActivityId           :
RelatedActivityId    :
ContainerLog         : Application
MatchedQueryIds      : {}
Bookmark             : System.Diagnostics.Eventing.Reader.EventBookmark
LevelDisplayName     : Errore
OpcodeDisplayName    : Informazioni
TaskDisplayName      :
KeywordsDisplayNames : {Classico}
Properties           : {System.Diagnostics.Eventing.Reader.EventProperty}

PS C:\Program Files\PowerShell\7>

**Comment by farag2** [comment]
Hi. Thanks for bug reporting. Unfortunately, 1.0.0.13 beta 2 is extremely outdated. :) Please test the latest build. It's much more stable and contains, as we know, only 4 bugs. :) Also it supports Windows 11 natively.

https://github.com/Sophia-Community/SophiApp/releases

Very soon we will release the stable build.
