### ISSUE TITLE
Dont support 22581.100

### ISSUE THREAD

**Issue by pomazanbohdan** [Sophia-Community/SophiApp#40]
### Prerequisites

- [ ] Verify that this is not a Windows issue;
- [ ] Refer to the [System requirements](https://github.com/Sophia-Community/SophiApp/blob/master/README.md#system-requirements);
- [ ] Attach a created log. You may find it in the app folder

### Expected behavior

![image](https://user-images.githubusercontent.com/696713/160392758-a5f1cf04-b76c-412f-997b-92ebdb6bfd9d.png)

### SophiApp version

1.0.0.38 RC6

### Windows Version

22581.100

### Logs

![image](https://user-images.githubusercontent.com/696713/160392867-11f8ca45-7b97-401a-91c6-0a948d730529.png)

**Comment by farag2** [comment]
Hi again. :) We're aware of this so called bug. We will add the Insider builds support only after the stable build release.

**Comment by farag2** [comment]
We always positioned this app for an average users. You've broken our dream)). I know that it has to support all current build. Everything will be, for sure after the release. We're very-very close to it.

**Comment by farag2** [comment]
Please check this build. Added the Insider support.
https://github.com/Sophia-Community/SophiApp/releases/tag/1.0.0.43

**Comment by pomazanbohdan** [comment]
Work
Thx

**Comment by farag2** [comment]
This is final version of the 1.0.0.x branch for today. All bugs that we've found are fixed. Time for the community to search for bugs. The only thing that will be changed is adding the Ukranian and German translations by natives. All are in progress...

**Comment by farag2** [comment]
Sophia Script will be updated soon to add the Insider support too.
