### ISSUE TITLE
Exe doesn't laucnh

### ISSUE THREAD

**Issue by GrahamboJangles** [Sophia-Community/SophiApp#43]
### Prerequisites

- [ ] Verify that this is not a Windows issue;
- [x] Refer to the [System requirements](https://github.com/Sophia-Community/SophiApp/blob/master/README.md#system-requirements);
- [x] Attach a created log. You may find it in the app folder

### Steps To Reproduce

1. Double Click SophiApp.exe
2. Wait eternally

### Expected behavior

i expected an app to run

### SophiApp version

1.0.0.43 RC12

### Windows Version

Windows 10 21H2 Build 19044.1586

### Logs

idk where the logs are

**Comment by GrahamboJangles** [comment]
Running as admin didn't even prompt, and didn't work either. Starting it with an elevated CMD worked, however...?

**Comment by farag2** [comment]
Run the PowerShell code that was provided in the issue template (you deleted it)

> idk where the logs are

There won't be any logs if app doesn't start for you...

> Running as admin didn't even prompt

No need to do it. The app has the manifest that elevate rights automatically.

> Starting it with an elevated CMD worked

Worked how? You can start the app?

**Comment by farag2** [comment]
Run this PowerShell code as admin (how-to) to find out what caused the program to crash, and attach the table, too.

 ```powershell
$HashTable = @{
   LogName = "Application"
   Id      = "1000"
}
Get-WinEvent -FilterHashtable $HashTable | Where-Object -FilterScript {($_.Level -eq "2") -and ($_.Message -match "SophiApp.exe")} | Select-Object -First 1 | Format-List -Property *

$HashTable = @{
   LogName = "Application"
   Id      = "1026"
}
Get-WinEvent -FilterHashtable $HashTable | Where-Object -FilterScript {($_.Level -eq "2") -and ($_.Message -match "SophiApp.exe")} | Select-Object -First 1 | Format-List -Property *

**Comment by GrahamboJangles** [comment]
> > Running as admin didn't even prompt
> 
> No need to do it. The app has the manifest that elevate rights automatically.
> 
I know, I just tried it anyways.

> > Starting it with an elevated CMD worked
> 
> Worked how? You can start the app?

Uhhh... yes. I think it might just be that my Windows is messed up.


I ran that Powershell code as admin in a .ps1 script and I got 
```
Get-WinEvent : No events were found that match the specified selection criteria.
At E:\Downloads\SophiApp\try.ps1:13 char:1
+ Get-WinEvent -FilterHashtable $HashTable | Where-Object -FilterScript ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-WinEvent], Exception
    + FullyQualifiedErrorId : NoMatchingEventsFound,Microsoft.PowerShell.Commands.GetWinEventCommand
```

yeah i think something is wrong with my windows thanks though lol

**Comment by farag2** [comment]
Strange OS you have. :) Butbthe app works well for rhe rest users)

**Comment by GrahamboJangles** [comment]
@farag2 that's what i get for removing bloatware and telemetry

**Comment by farag2** [comment]
There is no bloatware in Windows. :) Why all try to destroy your OS?)

**Comment by GrahamboJangles** [comment]
@farag2 I'm confused, do you not realize what this repository is for?

**Comment by farag2** [comment]
I'm confused too. :) No, this repo is not for destroying the OS for making it faster. This is a myth. All is a myth. Look at previews of all YouTubers making videos of how to configure Windows. They are just n00bs know nothings of how OS works. They just give bad advices for their audience that FPS can be increased by adding a registry key. Users believe them...
This app was made by us who work in IT. We get paid for it. We know how Windows works. Just read the description of it: https://github.com/Sophia-Community/SophiApp#about-sophiapp

> shows how Windows can be configured without making any harm to the OS.

This is true. All users do is lowering system stability by creating random reg keys, uninstalling system components and so on. We want to change it by showing what Windows can. It is not a monster. Yes, it does send telemetry. But is this bad? It makes OS better in the future. You're fool if you think diffently. How MS will know what we want if the OS doesn't send any data to the company? 🐱

**Comment by GrahamboJangles** [comment]
@farag2 idk people don't trust companies for some reason. Thanks for making the app though, it is one of the nicer ways to customize Windows
