### ISSUE TITLE
every thime i apply change app stuck

### ISSUE THREAD

**Issue by THEBOSSMAGNUS** [Sophia-Community/SophiApp#48]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [System requirements](https://github.com/Sophia-Community/SophiApp/blob/master/README.md#system-requirements);
- [X] SophiApp may not work on a homebrew Windows;
- [X] Attach a created log. You may find it in the `Logs` folder.

### Steps To Reproduce

every thime i apply change it stucks like that:
![image](https://user-images.githubusercontent.com/92474350/162509240-db1d5505-f509-4def-9112-91a3ce2ac7a2.png)
Anyway the change are done

### Expected behavior

....................

### Actual behaviour

........................................................

### Windows Version

Windows  21h2 22000.593 (insider release preview channel)

### SophiApp version

10.0.0.50

### SophiApp release type

Firefox

### Logs

[SophiApp-LENOVOIDEAPAD_3-132939185836626370.txt](https://github.com/Sophia-Community/SophiApp/files/8454633/SophiApp-LENOVOIDEAPAD_3-132939185836626370.txt)
[SophiApp-LENOVOIDEAPAD_3-132939182092069639.txt](https://github.com/Sophia-Community/SophiApp/files/8454634/SophiApp-LENOVOIDEAPAD_3-132939182092069639.txt)

**Comment by farag2** [comment]
I'll take a look at your logs on a business week. I think the 352 ID is the cause.

**Comment by THEBOSSMAGNUS** [comment]
One drive is uninstalled with this script

  ```
If (!(Test-Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\OneDrive")) {
        New-Item -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\OneDrive" | Out-Null
    }
    Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\OneDrive" -Name "DisableFileSyncNGSC" -Type DWord -Value 1
    Write-Host "Uninstalling OneDrive..."
    Stop-Process -Name "OneDrive" -ErrorAction SilentlyContinue
    Start-Sleep -s 2
    $onedrive = "$env:SYSTEMROOT\SysWOW64\OneDriveSetup.exe"
    If (!(Test-Path $onedrive)) {
        $onedrive = "$env:SYSTEMROOT\System32\OneDriveSetup.exe"
    }
    Start-Process $onedrive "/uninstall" -NoNewWindow -Wait
    Start-Sleep -s 2
    Stop-Process -Name "explorer" -ErrorAction SilentlyContinue
    Start-Sleep -s 2
    Remove-Item -Path "$env:USERPROFILE\OneDrive" -Force -Recurse -ErrorAction SilentlyContinue
    Remove-Item -Path "$env:LOCALAPPDATA\Microsoft\OneDrive" -Force -Recurse -ErrorAction SilentlyContinue
    Remove-Item -Path "$env:PROGRAMDATA\Microsoft OneDrive" -Force -Recurse -ErrorAction SilentlyContinue
    Remove-Item -Path "$env:SYSTEMDRIVE\OneDriveTemp" -Force -Recurse -ErrorAction SilentlyContinue
    If (!(Test-Path "HKCR:")) {
        New-PSDrive -Name HKCR -PSProvider Registry -Root HKEY_CLASSES_ROOT | Out-Null
    }
    Remove-Item -Path "HKCR:\CLSID\{018D5C66-4533-4307-9B53-224DE2ED1FE6}" -Recurse -ErrorAction SilentlyContinue
    Remove-Item -Path "HKCR:\Wow6432Node\CLSID\{018D5C66-4533-4307-9B53-224DE2ED1FE6}" -Recurse -ErrorAction SilentlyContinue
    Write-Host "Disabled OneDrive"
    $ResultText.text = "`r`n" +"`r`n" + "Deleted and Disabled OneDrive"
```

**Comment by farag2** [comment]
Ah, that was just our guess. Your log looks like legit. And the script you used too. We will get back to the bug on Monday.

**Comment by THEBOSSMAGNUS** [comment]
Our guess seems to be wrong. I tested on a VM with Onedrive uninstalled with that script and everything went well. I was on windows 10 and Eset(my av) wasn't installed

**Comment by farag2** [comment]
We guessed about that too. We need more time to get to this issue. Is the issue reproduced with the 53 build?

**Comment by THEBOSSMAGNUS** [comment]
Yes

**Comment by farag2** [comment]
Attach please new log.

**Comment by THEBOSSMAGNUS** [comment]
[SophiApp-LENOVOIDEAPAD_3-132941793134422579.txt](https://github.com/Sophia-Community/SophiApp/files/8467202/SophiApp-LENOVOIDEAPAD_3-132941793134422579.txt)
Here you are!

**Comment by farag2** [comment]
https://github.com/Sophia-Community/SophiApp/releases/tag/1.0.0.57
