### ISSUE TITLE
Crash disabling install last MSVC++

### ISSUE THREAD

**Issue by THEBOSSMAGNUS** [Sophia-Community/SophiApp#56]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [System requirements](https://github.com/Sophia-Community/SophiApp/blob/master/README.md#system-requirements);
- [X] SophiApp may not work on a homebrew Windows;
- [X] Attach a created log. You may find it in the `Logs` folder.

### Steps To Reproduce

1)disable install last MSVC++
2) apply

### Expected behavior

.

### Actual behaviour

.

### Windows Version

Windows  21h2 22000.651 (insider release preview channel)

### SophiApp version

10.0.0.54

### SophiApp release type

Firefox Beta

### Logs

[SophiApp-LENOVOIDEAPAD_3-132946837867474445.txt](https://github.com/Sophia-Community/SophiApp/files/8501919/SophiApp-LENOVOIDEAPAD_3-132946837867474445.txt)

**Comment by farag2** [comment]
I couldn't reproduce the bug. The app downloads and uninstalls the package without any issue.
Do you have this file: `C:\ProgramData\Package Cache\{2aaf1df0-eb13-4099-9992-962bb4e596d1}\vc_redist.x64.exe`

**Comment by farag2** [comment]
Also it'd be great if you provide me a remote access via e.g. TeamViewer. You can reach me via Telegram: @sanctuary_d

**Comment by THEBOSSMAGNUS** [comment]
> I couldn't reproduce the bug. The app downloads and uninstalls the package without any issue. Do you have this file: `C:\ProgramData\Package Cache\{2aaf1df0-eb13-4099-9992-962bb4e596d1}\vc_redist.x64.exe`

that file doesn't exist but MSVC are already installed

> Also it'd be great if you provide me a remote access via e.g. TeamViewer. You can reach me via Telegram: @sanctuary_d

Timezone?

**Comment by farag2** [comment]
MSK. I'm from Moscow: https://en.wikipedia.org/wiki/Moscow

**Comment by THEBOSSMAGNUS** [comment]
so you're one Hour later. Not a big problem. im'going to write you on tg

**Comment by THEBOSSMAGNUS** [comment]
Bug no longer appear in #63
