### ISSUE TITLE
Sequence contains no elements

### ISSUE THREAD

**Issue by truefriend-cz** [Sophia-Community/SophiApp#58]
### Prerequisites

- [ ] Verify that this is not a Windows issue;
- [ ] Refer to the [System requirements](https://github.com/Sophia-Community/SophiApp/blob/master/README.md#system-requirements);
- [ ] I do not use a homebrew Windows image;
- [ ] I did not tweak Windows before that could cause system instability;
- [ ] Attach a created log. You may find it in the `Logs` folder.

### Steps To Reproduce

After run app on Windows 11 and Windows 10 show this message only:
"Sequence contains no elements"
![image](https://user-images.githubusercontent.com/7845691/164306806-1dbaf42d-af6e-4f3d-96c3-f0343f731606.png)

### Expected behavior

-

### Actual behaviour

-

### Windows Version

Windows 11 and Windows 10

### SophiApp version

10.0.0.54 and 10.0.0.53

### SophiApp release type

SophiApp

### Logs

-

**Comment by farag2** [comment]
Hi. you didn't check all boxes in your issue. and didn't attach any log...

**Comment by truefriend-cz** [comment]
Where is a protocol saved?

**Comment by farag2** [comment]
You may find it in the `Logs` folder.

**Comment by farag2** [comment]
Edited you issue checkboxes. Please draw your attention

**Comment by truefriend-cz** [comment]
Log:
```
Windows 10 Enterprise G 21H2 build 19044.1645
Computer name: PC
User: Admin
User domain: PC
User culture: Czech (Czechia)
User region: Czechia
App version: 1.0.0.53
App is release: True
App folder: "D:\Data\Temp\SophiApp\"
App localization: EN
App theme: DARK

An error occurred during the startup OS condition check
Information: Sequence contains no elements
The method that caused the error: First

20.04.2022 21:29:02 Debug mode is: False
20.04.2022 21:29:02 Active view is: Loading
20.04.2022 21:29:02 Advanced settings is visible: False
20.04.2022 21:29:02 The "UWP for all users" switch state is: UNCHECKED
20.04.2022 21:29:02 The OS conditions checkings started
20.04.2022 21:29:02 OsVersionCondition: True
20.04.2022 21:29:02 OsBuildVersionCondition: True
20.04.2022 21:29:02 RebootRequiredCondition: True
20.04.2022 21:29:02 SingleInstanceCondition: True
20.04.2022 21:29:02 SingleAdminSessionCondition: True
20.04.2022 21:29:02 Win10TweakerCondition: True
20.04.2022 21:29:02 SycnexScriptCondition: True
20.04.2022 21:29:02 Active view is: SomethingWrong
20.04.2022 21:29:02 It took 0 second(s) to check the OS conditions

```

**Comment by farag2** [comment]
Strange. Did you tweak your OS?

**Comment by truefriend-cz** [comment]
No. It is clean install in default settings.
And i am installed (and using) this apps only: 
![image](https://user-images.githubusercontent.com/7845691/164308749-88571c94-1ae2-4c60-9436-78877feac76d.png)

**Comment by farag2** [comment]
It is so strange... Why the app works on every Windows but not yours? :)

**Comment by farag2** [comment]
So you didn't tweak it at all? Just installed those apps only?

**Comment by truefriend-cz** [comment]
Yes. I used to use different tweaking tools. Up to the NTLite level, and I went the way of removing components but it did cause problems. So I was looking for a suitable OS distribution that would work quickly and securely without unnecessary applications, advertisements, etc .. When I found the official version of "Enterprise G" that meets it.
I also tried the LTSC 2021 version but it was not safe enough and this installed advertising applications.

**Comment by truefriend-cz** [comment]
"Enterprise G" is different from other distributions in that it has Windows Defender completely disabled by default. So it doesn't have any anti-virus software .... it speeds up the operation of the OS quite a bit. Sometimes I check the OS with portable versions of antivirus applications.

**Comment by farag2** [comment]
Well.. Could your provide a link where you did you download it?

**Comment by farag2** [comment]
> "Enterprise G" is different from other distributions in that it has Windows Defender completely disabled by default. So it doesn't have any anti-virus software .... it speeds up the operation of the OS quite a bit. Sometimes I check the OS with portable versions of antivirus applications.

So you just approved right now that this is a homebrew image with a broken Defender?

**Comment by truefriend-cz** [comment]
Defender is not broken, but turned off by Microsoft from the factory (it is not removed but only deactivated without the possibility of turning it on - if you want antivirus, you must install another one)

**Comment by truefriend-cz** [comment]
I will not publish the link here, because Enterprise G cannot be downloaded by default - it is intended for governments and not for companies and end users. And it officially exists in only two language versions ... China and English.
This is for more information of this version... https://forums.mydigitallife.net/threads/windows-editions-reconstruction-project.80939/page-3

**Comment by truefriend-cz** [comment]
Have now at least found decent ISOs:

https://download.cmgos.com/oem/login

0101111011111

**Comment by truefriend-cz** [comment]
Or directly: https://archive.org/download/windows-10-china-government-edition-cmge_v2020-l.1207/CMGE_V2020-L.1207.iso

**Comment by farag2** [comment]
> Have now at least found decent ISOs:

Heard about his site.

> "Enterprise G" is "Windows 10 CMIT Government Edition"

I know about this special Windows version. But is that image from MDL the authentic image made by MS? Having read the thread I made a conclusion that it was customized. No?

**Comment by farag2** [comment]
I'm dpwnloading now `CMGE_V2022-L.1345.iso`. Why you sent a link to `CMGE_V2020-L.1207.iso`?

**Comment by farag2** [comment]
I will put it on test, because I guess what causes the bug. :) The Defender checkings. So it's pretty sure we will fix it.

**Comment by truefriend-cz** [comment]
I don't know which of the two is exactly her anymore. But thank you for testing.

**Comment by farag2** [comment]
It seems, we've fixed you bug. :)

**Comment by truefriend-cz** [comment]
Yes it is fixed. Thank you very much dev-god :)
Tested on version 1.0.0.58
