### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by SaiyajinK** [Sophia-Community/SophiApp#95]
### Your Idea

hi @farag2 ,

I made the French translation for SophiApp (v1.0.0.71) ! 

> [SophiApp French translation.zip](https://github.com/Sophia-Community/SophiApp/files/9128739/SophiApp.French.translation.zip)

The French language having a lot of special symbols (é, ê, ë, î, à, ç, ù) I could notice on the first reading of the English translation that there were some html tags `-&quot;-` and `-&#174-` so I asked myself the question of whether to include these tags in the French translation. Not knowing I made two versions: One with the normal text and the other with the tags of the special characters of French.

I hope I have made myself understood

Please include the translation!

**EDIT** : once the update of the app with the included translation is available, I will be able to see if I may need to improve the translation. :

### SophiApp Version

1.0.0.71

### Windows Version

Windows 11 Pro 22H1 (local) & 22h2 (virtual)

**Comment by farag2** [comment]
Thank you. But can you create a PR?)
