### ISSUE TITLE
Windows 11 taskbar internet/audio icon left click not working.

### ISSUE THREAD

**Issue by farzher** [Sophia-Community/SophiApp#96]
i did a fresh win 11 install, then ran SophiApp to remove/disable a bunch of stuff.

left clicking these 2 icons won't show the popup window. 

![image](https://user-images.githubusercontent.com/1005136/179662412-507ab479-e647-4730-b664-fc478db46e87.png)

i can't figure out what i did to break it. thought you guys might know. is this something SophiApp even has the ability to break?
maybe it's just a windows bug. if this probably wasn't caused by SophiApp feel free to just close the issue.

**Comment by farzher** [comment]
nvm. it was broken because i disabled the `Touch Keyboard and Handwriting Panel Service`

i'm on a desktop, don't have a touch anything. be careful when disabling services .-.

**Comment by farag2** [comment]
You too. :)
