### ISSUE TITLE
Disable telemetry issue (probably with insider builds)

### ISSUE THREAD

**Issue by THEBOSSMAGNUS** [Sophia-Community/SophiApp#98]
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [X] Refer to the [System requirements](https://github.com/Sophia-Community/SophiApp/blob/master/README.md#system-requirements);
- [X] I do not use a homebrew Windows image;
- [ ] I did not tweak Windows before that could cause system instability;
- [x] Attach a created log. You may find it in the `Logs` folder.

### Steps To Reproduce

1. (probably) use an insider build
2. Use the disable telemetry service tweak
3. apply
4. 
![image](https://user-images.githubusercontent.com/92474350/182028719-870d1eff-0c03-4a6d-8024-cabd22555e4a.png)

### Expected behavior

A correct message that displays impossible to disable telemetry on insider builds.

### Actual behaviour

![image](https://user-images.githubusercontent.com/92474350/182028749-fbe94eba-250e-4cfd-919f-9cc77a9881c9.png)

### Windows Version

22621.317

### SophiApp version

1.0.71/1.0.75

### SophiApp release type

Both

### Logs

[Uploading SophiApp-IDEAPAD315ADA5-133037474708114092.txt…]()

**Comment by farag2** [comment]
It was the Windows issue. Closing...
