### ISSUE TITLE
Increase Resolution for SophiApp.ico

### ISSUE THREAD

**Issue by kezcik** [Sophia-Community/SophiApp#99]
### Your Idea

Currently the SophiApp.ico file only includes a 32x32 file however I have created a 256x256, 64x64, 48x48, 32x32 and 16x16 ico file by converting svg file to a 256x256 png and then creating the icon file.

https://github.com/kezcik/SophiApp/blob/c112e9605874a62490952856fc184c7772934279/SophiApp/SophiApp/SophiApp.ico

This should be merged

### SophiApp Version

1.0.0.71

### Windows Version

Windows 10

### Comments

is this something that can be added / fixed?

**Comment by farag2** [comment]
Merged in #101
